function onSay(cid, words, param)
	if isPlayer(cid) == 1 and param ~= "" and getPlayerAccess(cid) > 0 then
		local pos = getCreaturePosition(cid)
		doSendDistanceShoot(pos, {x = pos.x - 7, y = pos.y - 4, z = pos.z}, param)
		doSendDistanceShoot(pos, {x = pos.x - 7, y = pos.y - 3, z = pos.z}, param)
		doSendDistanceShoot(pos, {x = pos.x - 7, y = pos.y - 2, z = pos.z}, param)
		doSendDistanceShoot(pos, {x = pos.x - 7, y = pos.y - 1, z = pos.z}, param)
		doSendDistanceShoot(pos, {x = pos.x - 7, y = pos.y, z = pos.z}, param)
		doSendDistanceShoot(pos, {x = pos.x - 7, y = pos.y + 1, z = pos.z}, param)
		doSendDistanceShoot(pos, {x = pos.x - 7, y = pos.y + 2, z = pos.z}, param)
		doSendDistanceShoot(pos, {x = pos.x - 7, y = pos.y + 3, z = pos.z}, param)
		doSendDistanceShoot(pos, {x = pos.x - 7, y = pos.y + 4, z = pos.z}, param)
		doSendDistanceShoot(pos, {x = pos.x - 7, y = pos.y + 5, z = pos.z}, param)
		doSendDistanceShoot(pos, {x = pos.x + 7, y = pos.y - 5, z = pos.z}, param)
		doSendDistanceShoot(pos, {x = pos.x + 7, y = pos.y - 4, z = pos.z}, param)
		doSendDistanceShoot(pos, {x = pos.x + 7, y = pos.y - 3, z = pos.z}, param)
		doSendDistanceShoot(pos, {x = pos.x + 7, y = pos.y - 2, z = pos.z}, param)
		doSendDistanceShoot(pos, {x = pos.x + 7, y = pos.y - 1, z = pos.z}, param)
		doSendDistanceShoot(pos, {x = pos.x + 7, y = pos.y, z = pos.z}, param)
		doSendDistanceShoot(pos, {x = pos.x + 7, y = pos.y + 1, z = pos.z}, param)
		doSendDistanceShoot(pos, {x = pos.x + 7, y = pos.y + 2, z = pos.z}, param)
		doSendDistanceShoot(pos, {x = pos.x + 7, y = pos.y + 3, z = pos.z}, param)
		doSendDistanceShoot(pos, {x = pos.x + 7, y = pos.y + 4, z = pos.z}, param)
		doSendDistanceShoot(pos, {x = pos.x + 7, y = pos.y + 5, z = pos.z}, param)
		doSendDistanceShoot(pos, {x = pos.x - 7, y = pos.y - 5, z = pos.z}, param)
		doSendDistanceShoot(pos, {x = pos.x - 6, y = pos.y - 5, z = pos.z}, param)
		doSendDistanceShoot(pos, {x = pos.x - 5, y = pos.y - 5, z = pos.z}, param)
		doSendDistanceShoot(pos, {x = pos.x - 4, y = pos.y - 5, z = pos.z}, param)
		doSendDistanceShoot(pos, {x = pos.x - 3, y = pos.y - 5, z = pos.z}, param)
		doSendDistanceShoot(pos, {x = pos.x - 2, y = pos.y - 5, z = pos.z}, param)
		doSendDistanceShoot(pos, {x = pos.x - 1, y = pos.y - 5, z = pos.z}, param)
		doSendDistanceShoot(pos, {x = pos.x, y = pos.y - 5, z = pos.z}, param)
		doSendDistanceShoot(pos, {x = pos.x + 1, y = pos.y - 5, z = pos.z}, param)
		doSendDistanceShoot(pos, {x = pos.x + 2, y = pos.y - 5, z = pos.z}, param)
		doSendDistanceShoot(pos, {x = pos.x + 3, y = pos.y - 5, z = pos.z}, param)
		doSendDistanceShoot(pos, {x = pos.x + 4, y = pos.y - 5, z = pos.z}, param)
		doSendDistanceShoot(pos, {x = pos.x + 5, y = pos.y - 5, z = pos.z}, param)
		doSendDistanceShoot(pos, {x = pos.x + 6, y = pos.y - 5, z = pos.z}, param)
		doSendDistanceShoot(pos, {x = pos.x - 6, y = pos.y + 5, z = pos.z}, param)
		doSendDistanceShoot(pos, {x = pos.x - 5, y = pos.y + 5, z = pos.z}, param)
		doSendDistanceShoot(pos, {x = pos.x - 4, y = pos.y + 5, z = pos.z}, param)
		doSendDistanceShoot(pos, {x = pos.x - 3, y = pos.y + 5, z = pos.z}, param)
		doSendDistanceShoot(pos, {x = pos.x - 2, y = pos.y + 5, z = pos.z}, param)
		doSendDistanceShoot(pos, {x = pos.x - 1, y = pos.y + 5, z = pos.z}, param)
		doSendDistanceShoot(pos, {x = pos.x, y = pos.y + 5, z = pos.z}, param)
		doSendDistanceShoot(pos, {x = pos.x + 1, y = pos.y + 5, z = pos.z}, param)
		doSendDistanceShoot(pos, {x = pos.x + 2, y = pos.y + 5, z = pos.z}, param)
		doSendDistanceShoot(pos, {x = pos.x + 3, y = pos.y + 5, z = pos.z}, param)
		doSendDistanceShoot(pos, {x = pos.x + 4, y = pos.y + 5, z = pos.z}, param)
		doSendDistanceShoot(pos, {x = pos.x + 5, y = pos.y + 5, z = pos.z}, param)
		doSendDistanceShoot(pos, {x = pos.x + 6, y = pos.y + 5, z = pos.z}, param)
	end
end